#!/bin/bash
## these files have been edited to reflect persistent environment


ROOT=/home/mzadig/source/voltha/k8s
cd /home/mzadig/source/voltha/k8s

echo $ROOT


### VOLTHA CORE AND ACCESSORY CONTAINERS ####
kubectl delete -f $ROOT/foundry-node/envoy_for_consul_repo.yml 

# check the pods to be sure they are down

kubectl get pods -n voltha
