#!/bin/bash
## these files have been edited to reflect persistent environment
cd /home/mzadig/source/voltha/k8s


kubectl delete -f foundry-node/vcore_for_consul_repo.yml
kubectl apply -f foundry-node/vcore_for_consul_repo.yml

# verify all the pods are running

kubectl get pods -n voltha
