#!/bin/bash
# this will reardown everything and reboot 


echo "============== Beginning ============================"
#
# Completely teardown and voltha and k8s
# purging all containers and images
#

cd ~/source/voltha/k8s

# remove all running voltha services
kubectl delete -f foundry-node/

# remove the running k8s cluster
sudo kubeadm reset

# remove all leftover containers and images
sudo docker system prune --all

# clear out voltha persistent data
sudo rm -rf /var/lib/voltha-runtime

# remove repo reference
#sudo rm /etc/docker/daemon.json

# remove local user credentials for removed k8s
rm -rf ~/.kube


read -r -p "Are you sure you want to reboot? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    echo "Rebooting ============================"
    reboot
else
    echo "Exting:  No reboot ====================="
fi

