#!/bin/bash
## these files have been edited to reflect persistent environment
cd /home/mzadig/source/voltha/k8s

### VOLTHA CORE AND ACCESSORY CONTAINERS ####
echo 'starting namespace'
kubectl apply -f namespace.yml

echo 'Starting ingress'
kubectl apply -f ingress/

kubectl apply -f foundry-node/zookeeper_persist.yml
kubectl apply -f foundry-node/kafka_persist.yml
kubectl apply -f foundry-node/consul_persist.yml
kubectl apply -f foundry-node/fluentd.yml



echo 'consul'
kubectl apply -f foundry-node/vcore_for_consul_repo.yml
echo ' foundry-node/ofagent_repo.yml '
kubectl apply -f foundry-node/ofagent_repo.yml 
echo 'foundry-node/envoy_for_consul_repo.yml'
kubectl apply -f foundry-node/envoy_for_consul_repo.yml 
echo 'foundry-node/vcli_repo.yml '
kubectl apply -f foundry-node/vcli_repo.yml 
echo ' foundry-node/netconf_repo.ym '
kubectl apply -f foundry-node/netconf_repo.yml 
echo ' foundry-node/grafana_persist.yml  '
kubectl apply -f foundry-node/grafana_persist.yml 
echo ' foundry-node/stats_repo.yml '
kubectl apply -f foundry-node/stats_repo.yml 
echo 'foundry-node/onos_repo.yml  '
kubectl apply -f foundry-node/onos_repo.yml 

# verify all the pods are running

kubectl get pods -n voltha
