#!/bin/bash
## these files have been edited to reflect persistent environment


cd /home/foundry/source/voltha/k8s


### VOLTHA CORE AND ACCESSORY CONTAINERS ####
echo "Running -----------  kubectl delete -f $ROOT/foundry-node/kafka_persist.yml"
kubectl delete -f foundry-node/kafka_persist.yml
#kubectl delete -f foundry-node/zookeeper_persist.yml

echo 'Running -----   foundry-node/kafka_persist.yml'
#kubectl apply -f foundry-node/zookeeper_persist.yml
kubectl apply -f foundry-node/kafka_persist.yml

# verify all the pods are running

kubectl get pods -n voltha
