#!/bin/bash

# This script will show the current running voltha cmdr IF it is running
# AND if it is running it will pull the PID and kill it

ps -alx | grep 'firefox'| grep -v 'killfirefox' | grep -Fv 'grep' 

# Get the pid
CUR_PID=`ps -ef | grep 'firefox' | grep -v 'killfirefox' | grep -Fv 'grep' | awk '{print $2}'`
echo "Killing  pid = " $CUR_PID

kill $CUR_PID


