#!/bin/bash

# This script will show the current running voltha cmdr IF it is running
# AND if it is running it will pull the PID and kill it

ps -alx | grep -F '/usr/bin/python3 ./volthacmdr.py'| grep -Fv 'grep' 

# Get the pid
CUR_PID=`ps -ef | grep '/usr/bin/python3 ./volthacmdr.py' | grep -Fv 'grep' | awk '{print $2}'`
echo "Killing  pid = " $CUR_PID
kill $CUR_PID


