#!/bin/bash

#Stop containers
cd /home/mzadig/source/voltha

kubectl delete -f k8s/foundry-node/

#Flush stored data
echo "removing consul/data/*"
sudo rm -r /var/lib/voltha-runtime/consul/data/*
echo "removing fluentd/data/*"
sudo rm -r /var/lib/voltha-runtime/fluentd/*
echo "removing kafka/data/*"
sudo rm -r /var/lib/voltha-runtime/kafka/*
echo "removing zookeeper/data/*"
sudo rm -r /var/lib/voltha-runtime/zookeeper/data/*
echo "removing zookeeper/datalog/*"
sudo rm -r /var/lib/voltha-runtime/zookeeper/datalog/*
echo "removing grafana/data/*"
sudo rm -r /var/lib/voltha-runtime/grafana/data/*

#Reapply/recreate containers
kubectl apply -f k8s/foundry-node/zookeeper_persist.yml
kubectl apply -f k8s/foundry-node/kafka_persist.yml
kubectl apply -f k8s/foundry-node/consul_persist.yml
kubectl apply -f k8s/foundry-node/fluentd.yml
kubectl apply -f k8s/foundry-node/vcore_for_consul_repo.yml
kubectl apply -f k8s/foundry-node/ofagent_repo.yml
kubectl apply -f k8s/foundry-node/envoy_for_consul_repo.yml
kubectl apply -f k8s/foundry-node/vcli_repo.yml
kubectl apply -f k8s/foundry-node/netconf_repo.yml
kubectl apply -f k8s/foundry-node/grafana_persist.yml
kubectl apply -f k8s/foundry-node/stats_repo.yml
kubectl apply -f k8s/foundry-node/onos_repo.yml

#Show resulting containers
kubectl get pod -n voltha
kubectl get svc -n voltha
