#!/bin/bash

#"This will collect the pod name in the voltha cluser based on the  key word"

KEY=$1

POD_NAME="notfound"
kubectl -n voltha get pods | while read LINE
	do
		VAL=$LINE
		VAL=`awk '{print $1}' <<< $LINE`
		
		case $VAL in 
			$KEY*)  echo "$VAL"
				break;;
			*) FOO="foo";;
		esac
	done 




