#!/bin/bash
## these files have been edited to reflect persistent environment
cd /home/mzadig/source/voltha/k8s


# verify all the pods are running

kubectl get pods -n voltha
kubectl get svc -n voltha

