#!/bin/bash
## these files have been edited to reflect persistent environment


ROOT=/home/foundry/source/voltha/k8s
cd /home/foundry/source/voltha/k8s

echo $ROOT


### VOLTHA CORE AND ACCESSORY CONTAINERS ####

echo "kubectl delete -f $ROOT/vcore_for_etcd_repo_msz.yml"
kubectl delete -f $ROOT/foundry-node/vcore_for_etcd_repo_msz.yml 

echo "kubectl apply -f $ROOT/vcore_for_etcd_repo_msz.yml"
kubectl apply -f $ROOT/foundry-node/vcore_for_etcd_repo_msz.yml 

# check the pods to be sure they are dvack up ......

kubectl get pods -n voltha -o wide -w
