#!/bin/bash
## these files have been edited to reflect persistent environment
cd /home/mzadig/source/voltha/k8s

echo 'This will delete the k8 instance of foundry-node/vcore_for_consul_repo.yml'
kubectl delete -f foundry-node/vcore_for_consul_repo.yml

# verify all the pods are running

kubectl get pods -n voltha
