FROM ubuntu:xenial

# Install app dependencies
RUN apt-get update && \
	apt-get install net-tools -y && \
	apt-get install iputils-ping -y && \
	apt-get install kafkacat -y && \
	apt-get install curl -y && \
	apt-get install dnsutils -y && \
	apt-get update


